/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LandRegistry__factory } from "./LandRegistry__factory";
export { Ownership__factory } from "./Ownership__factory";
export { Verification__factory } from "./Verification__factory";
