/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LandRegistry } from "./LandRegistry";
export type { Ownership } from "./Ownership";
export type { Verification } from "./Verification";
export * as factories from "./factories";
export { LandRegistry__factory } from "./factories/LandRegistry__factory";
export { Ownership__factory } from "./factories/Ownership__factory";
export { Verification__factory } from "./factories/Verification__factory";
