/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LandRegistry {
  export type ParcelStruct = {
    id: BigNumberish;
    titleNumber: string;
    location: string;
    ipfsHash: string;
    owner: AddressLike;
    status: BigNumberish;
  };

  export type ParcelStructOutput = [
    id: bigint,
    titleNumber: string,
    location: string,
    ipfsHash: string,
    owner: string,
    status: bigint
  ] & {
    id: bigint;
    titleNumber: string;
    location: string;
    ipfsHash: string;
    owner: string;
    status: bigint;
  };
}

export interface LandRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveParcel"
      | "getParcel"
      | "officer"
      | "parcelCount"
      | "parcels"
      | "rejectParcel"
      | "submitParcel"
      | "titleExists"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ParcelApproved"
      | "ParcelRejected"
      | "ParcelSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveParcel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParcel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "officer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "parcelCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "parcels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectParcel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitParcel",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "titleExists", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "approveParcel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getParcel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "officer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parcelCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "parcels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectParcel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitParcel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "titleExists",
    data: BytesLike
  ): Result;
}

export namespace ParcelApprovedEvent {
  export type InputTuple = [parcelId: BigNumberish, officer: AddressLike];
  export type OutputTuple = [parcelId: bigint, officer: string];
  export interface OutputObject {
    parcelId: bigint;
    officer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParcelRejectedEvent {
  export type InputTuple = [parcelId: BigNumberish, officer: AddressLike];
  export type OutputTuple = [parcelId: bigint, officer: string];
  export interface OutputObject {
    parcelId: bigint;
    officer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParcelSubmittedEvent {
  export type InputTuple = [
    parcelId: BigNumberish,
    owner: AddressLike,
    titleNumber: string
  ];
  export type OutputTuple = [
    parcelId: bigint,
    owner: string,
    titleNumber: string
  ];
  export interface OutputObject {
    parcelId: bigint;
    owner: string;
    titleNumber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LandRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LandRegistry;
  waitForDeployment(): Promise<this>;

  interface: LandRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveParcel: TypedContractMethod<
    [_parcelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getParcel: TypedContractMethod<
    [_parcelId: BigNumberish],
    [LandRegistry.ParcelStructOutput],
    "view"
  >;

  officer: TypedContractMethod<[], [string], "view">;

  parcelCount: TypedContractMethod<[], [bigint], "view">;

  parcels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint] & {
        id: bigint;
        titleNumber: string;
        location: string;
        ipfsHash: string;
        owner: string;
        status: bigint;
      }
    ],
    "view"
  >;

  rejectParcel: TypedContractMethod<
    [_parcelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitParcel: TypedContractMethod<
    [_titleNumber: string, _location: string, _ipfsHash: string],
    [bigint],
    "nonpayable"
  >;

  titleExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveParcel"
  ): TypedContractMethod<[_parcelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getParcel"
  ): TypedContractMethod<
    [_parcelId: BigNumberish],
    [LandRegistry.ParcelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "officer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "parcelCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "parcels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint] & {
        id: bigint;
        titleNumber: string;
        location: string;
        ipfsHash: string;
        owner: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rejectParcel"
  ): TypedContractMethod<[_parcelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitParcel"
  ): TypedContractMethod<
    [_titleNumber: string, _location: string, _ipfsHash: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "titleExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;

  getEvent(
    key: "ParcelApproved"
  ): TypedContractEvent<
    ParcelApprovedEvent.InputTuple,
    ParcelApprovedEvent.OutputTuple,
    ParcelApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ParcelRejected"
  ): TypedContractEvent<
    ParcelRejectedEvent.InputTuple,
    ParcelRejectedEvent.OutputTuple,
    ParcelRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ParcelSubmitted"
  ): TypedContractEvent<
    ParcelSubmittedEvent.InputTuple,
    ParcelSubmittedEvent.OutputTuple,
    ParcelSubmittedEvent.OutputObject
  >;

  filters: {
    "ParcelApproved(uint256,address)": TypedContractEvent<
      ParcelApprovedEvent.InputTuple,
      ParcelApprovedEvent.OutputTuple,
      ParcelApprovedEvent.OutputObject
    >;
    ParcelApproved: TypedContractEvent<
      ParcelApprovedEvent.InputTuple,
      ParcelApprovedEvent.OutputTuple,
      ParcelApprovedEvent.OutputObject
    >;

    "ParcelRejected(uint256,address)": TypedContractEvent<
      ParcelRejectedEvent.InputTuple,
      ParcelRejectedEvent.OutputTuple,
      ParcelRejectedEvent.OutputObject
    >;
    ParcelRejected: TypedContractEvent<
      ParcelRejectedEvent.InputTuple,
      ParcelRejectedEvent.OutputTuple,
      ParcelRejectedEvent.OutputObject
    >;

    "ParcelSubmitted(uint256,address,string)": TypedContractEvent<
      ParcelSubmittedEvent.InputTuple,
      ParcelSubmittedEvent.OutputTuple,
      ParcelSubmittedEvent.OutputObject
    >;
    ParcelSubmitted: TypedContractEvent<
      ParcelSubmittedEvent.InputTuple,
      ParcelSubmittedEvent.OutputTuple,
      ParcelSubmittedEvent.OutputObject
    >;
  };
}
