/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Ownership {
  export type TransferStruct = {
    parcelId: BigNumberish;
    from: AddressLike;
    to: AddressLike;
    timestamp: BigNumberish;
    confirmed: boolean;
  };

  export type TransferStructOutput = [
    parcelId: bigint,
    from: string,
    to: string,
    timestamp: bigint,
    confirmed: boolean
  ] & {
    parcelId: bigint;
    from: string;
    to: string;
    timestamp: bigint;
    confirmed: boolean;
  };
}

export interface OwnershipInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confirmTransfer"
      | "currentOwner"
      | "getHistory"
      | "initiateTransfer"
      | "pendingTransfer"
      | "setInitialOwner"
      | "transferHistory"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TransferConfirmed" | "TransferInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confirmTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setInitialOwner",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferHistory",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHistory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInitialOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferHistory",
    data: BytesLike
  ): Result;
}

export namespace TransferConfirmedEvent {
  export type InputTuple = [
    parcelId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [parcelId: bigint, from: string, to: string];
  export interface OutputObject {
    parcelId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    parcelId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [parcelId: bigint, from: string, to: string];
  export interface OutputObject {
    parcelId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Ownership extends BaseContract {
  connect(runner?: ContractRunner | null): Ownership;
  waitForDeployment(): Promise<this>;

  interface: OwnershipInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confirmTransfer: TypedContractMethod<
    [_parcelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentOwner: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getHistory: TypedContractMethod<
    [_parcelId: BigNumberish],
    [Ownership.TransferStructOutput[]],
    "view"
  >;

  initiateTransfer: TypedContractMethod<
    [_parcelId: BigNumberish, _buyer: AddressLike],
    [void],
    "nonpayable"
  >;

  pendingTransfer: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        parcelId: bigint;
        from: string;
        to: string;
        timestamp: bigint;
        confirmed: boolean;
      }
    ],
    "view"
  >;

  setInitialOwner: TypedContractMethod<
    [_parcelId: BigNumberish, _owner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        parcelId: bigint;
        from: string;
        to: string;
        timestamp: bigint;
        confirmed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confirmTransfer"
  ): TypedContractMethod<[_parcelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentOwner"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getHistory"
  ): TypedContractMethod<
    [_parcelId: BigNumberish],
    [Ownership.TransferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [_parcelId: BigNumberish, _buyer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingTransfer"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        parcelId: bigint;
        from: string;
        to: string;
        timestamp: bigint;
        confirmed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setInitialOwner"
  ): TypedContractMethod<
    [_parcelId: BigNumberish, _owner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        parcelId: bigint;
        from: string;
        to: string;
        timestamp: bigint;
        confirmed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TransferConfirmed"
  ): TypedContractEvent<
    TransferConfirmedEvent.InputTuple,
    TransferConfirmedEvent.OutputTuple,
    TransferConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;

  filters: {
    "TransferConfirmed(uint256,address,address)": TypedContractEvent<
      TransferConfirmedEvent.InputTuple,
      TransferConfirmedEvent.OutputTuple,
      TransferConfirmedEvent.OutputObject
    >;
    TransferConfirmed: TypedContractEvent<
      TransferConfirmedEvent.InputTuple,
      TransferConfirmedEvent.OutputTuple,
      TransferConfirmedEvent.OutputObject
    >;

    "TransferInitiated(uint256,address,address)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
  };
}
