/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LandRegistry {
  export type ParcelStruct = {
    id: BigNumberish;
    titleNumber: string;
    location: string;
    ipfsHash: string;
    owner: AddressLike;
    status: BigNumberish;
  };

  export type ParcelStructOutput = [
    id: bigint,
    titleNumber: string,
    location: string,
    ipfsHash: string,
    owner: string,
    status: bigint
  ] & {
    id: bigint;
    titleNumber: string;
    location: string;
    ipfsHash: string;
    owner: string;
    status: bigint;
  };
}

export declare namespace Ownership {
  export type TransferStruct = {
    parcelId: BigNumberish;
    from: AddressLike;
    to: AddressLike;
    timestamp: BigNumberish;
    confirmed: boolean;
  };

  export type TransferStructOutput = [
    parcelId: bigint,
    from: string,
    to: string,
    timestamp: bigint,
    confirmed: boolean
  ] & {
    parcelId: bigint;
    from: string;
    to: string;
    timestamp: bigint;
    confirmed: boolean;
  };
}

export interface VerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getParcelDetails"
      | "getTransferHistory"
      | "ownership"
      | "registry"
      | "verifyOwner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getParcelDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ownership", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyOwner",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getParcelDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyOwner",
    data: BytesLike
  ): Result;
}

export interface Verification extends BaseContract {
  connect(runner?: ContractRunner | null): Verification;
  waitForDeployment(): Promise<this>;

  interface: VerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getParcelDetails: TypedContractMethod<
    [_parcelId: BigNumberish],
    [
      [LandRegistry.ParcelStructOutput, string] & {
        parcel: LandRegistry.ParcelStructOutput;
        owner: string;
      }
    ],
    "view"
  >;

  getTransferHistory: TypedContractMethod<
    [_parcelId: BigNumberish],
    [Ownership.TransferStructOutput[]],
    "view"
  >;

  ownership: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  verifyOwner: TypedContractMethod<[_parcelId: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getParcelDetails"
  ): TypedContractMethod<
    [_parcelId: BigNumberish],
    [
      [LandRegistry.ParcelStructOutput, string] & {
        parcel: LandRegistry.ParcelStructOutput;
        owner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransferHistory"
  ): TypedContractMethod<
    [_parcelId: BigNumberish],
    [Ownership.TransferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownership"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyOwner"
  ): TypedContractMethod<[_parcelId: BigNumberish], [string], "view">;

  filters: {};
}
